from __future__ import annotations

import math
from typing import Any

from memory_control.core.config import RunConfig
from memory_control.core.types import ControllerState, Knobs


TELEMETRY_FIELDS = [
    "step",
    "samples",
    "step_s",
    "compute_s",
    "comm_s",
    "io_s",
    "comm_frac",
    "io_frac",
    "peak_mb",
    "proxy_peak_mb",
    "cuda_peak_allocated_mb",
    "cuda_peak_reserved_mb",
    "memory_source",
    "budget_mb",
    "safe_limit_mb",
    "oom",
    "micro_batch",
    "grad_accum_steps",
    "next_micro_batch",
    "next_grad_accum_steps",
    "controller",
    "knob_changed",
    "controller_action",
    "safety_allowed",
    "safety_reason",
    "model_name",
    "dataset_name",
    "precision",
    "compile_model",
    "distributed",
    "rank",
    "world_size",
    "model_parameters",
    "model_input_shape",
    "loss",
    "effective_samples_per_s",
    "best_safe_throughput",
]


def make_telemetry_row(
    *,
    step: int,
    effective_samples: int,
    step_s: float,
    compute_s: float,
    comm_s: float,
    io_s: float,
    comm_frac: float,
    io_frac: float,
    peak_mb: float,
    proxy_peak_mb: float,
    cuda_peak_allocated_mb: float,
    cuda_peak_reserved_mb: float,
    memory_source: str,
    oom: bool,
    step_knobs: Knobs,
    next_knobs: Knobs,
    cfg: RunConfig,
    knob_changed: bool,
    controller_state: ControllerState,
    model_profile: Any,
    distributed: bool,
    rank: int,
    world_size: int,
    model_parameters: int,
    total_loss: float,
    effective_samples_per_s: float,
) -> dict[str, object]:
    return {
        "step": step,
        "samples": effective_samples,
        "step_s": f"{step_s:.8f}",
        "compute_s": f"{compute_s:.8f}",
        "comm_s": f"{comm_s:.8f}",
        "io_s": f"{io_s:.8f}",
        "comm_frac": f"{comm_frac:.8f}",
        "io_frac": f"{io_frac:.8f}",
        "peak_mb": f"{peak_mb:.4f}",
        "proxy_peak_mb": f"{proxy_peak_mb:.4f}",
        "cuda_peak_allocated_mb": f"{cuda_peak_allocated_mb:.4f}",
        "cuda_peak_reserved_mb": f"{cuda_peak_reserved_mb:.4f}",
        "memory_source": memory_source,
        "budget_mb": f"{cfg.budget_mb:.4f}",
        "safe_limit_mb": f"{cfg.budget_mb * (1.0 - cfg.headroom_margin):.4f}",
        "oom": int(oom),
        "micro_batch": step_knobs.micro_batch,
        "grad_accum_steps": step_knobs.grad_accum_steps,
        "next_micro_batch": next_knobs.micro_batch,
        "next_grad_accum_steps": next_knobs.grad_accum_steps,
        "controller": cfg.controller,
        "knob_changed": int(knob_changed),
        "controller_action": controller_state.last_action_name,
        "safety_allowed": int(controller_state.last_safety_allowed),
        "safety_reason": controller_state.last_safety_reason,
        "model_name": model_profile.name,
        "dataset_name": cfg.dataset_name,
        "precision": cfg.precision,
        "compile_model": int(bool(cfg.compile_model)),
        "distributed": int(bool(distributed)),
        "rank": rank,
        "world_size": world_size,
        "model_parameters": model_parameters,
        "model_input_shape": "x".join(str(dim) for dim in model_profile.input_shape),
        "loss": f"{total_loss:.6f}" if math.isfinite(total_loss) else "nan",
        "effective_samples_per_s": f"{effective_samples_per_s:.8f}",
        "best_safe_throughput": f"{controller_state.best_throughput:.8f}",
    }
